### ISSUE TITLE
Exit button doesn't work

### ISSUE THREAD

**Issue by AravindIM** [AbstractTeamZ/fabricator-ide#2]

**Comment by isabelacmor** [comment]
I'd like to pick this up. Can you give more context? I'm assuming the "exit button" is `id="exit-icon"` in `mainwindow.html`. What is the expected behavior?

**Comment by lukasleeyo** [comment]
Hello there, I have worked on the issue and submitted the PR request. Please verify the application, thanks :)

**Comment by AravindIM** [comment]
@isabelacmor It should close the window

**Comment by AravindIM** [comment]
@lukasleeyo thanks for your contribution... I'll verify it and merge it...
