### ISSUE TITLE
Clear search button not functional

### ISSUE THREAD

**Issue by AravindIM** [AbstractTeamZ/fabricator-ide#7]
The clear search button inside the search bar does clear whatever is typed into the search bar on clicking it. It is missing functionality.

**Comment by Robbatron** [comment]
I know nothing about Electron so I don't know best practices, but I can pick this one up and write a function that clears the field and call it the same way exitApp() is called. Sound good?

**Comment by Robbatron** [comment]
https://github.com/AbstractTeamZ/fabricator-ide/pull/8

**Comment by AravindIM** [comment]
> I know nothing about Electron so I don't know best practices, but I can pick this one up and write a function that clears the field and call it the same way exitApp() is called. Sound good?

Yep, that should do fine. Checkout electron docs. It's just makes it to launch in a stripped-down version of chromium. It's really easy.

Thankyou for your contribution. We'd really appreciate if you "watch" this repo, and help us in making this IDE. As you can see our there's more work to be done. Any help will be much appreciated.

Goodluck for Hacktoberfest!
